theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "wireless"
ssid = true
speed_up = true
speed_down = true

[[block]]
block = "net"
device = "aukey-ethernet"
speed_up = true
speed_down = true
hide_missing = true

#[[block]]
#block = "bluetooth"
#mac = "60:F2:62:15:55:DF"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 60
warning = 1.0
alert = 0.5

[[block]]
block = "disk_space"
path = "/home"
alias = "home"
info_type = "available"
unit = "GB"
interval = 60
warning = 10.0
alert = 5.0

[[block]]
block = "disk_space"
path = "/nix"
alias = "nix"
info_type = "available"
unit = "GB"
interval = 60
warning = 5.0
alert = 2.0

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}°C"
chip = "*-isa-*"

[[block]]
block = "nvidia_gpu"
label = "GT 1030"
show_memory = false
show_clocks = true
interval = 1

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "sound"

[[block]]
block = "xrandr"
icons = true
interval = 10

[[block]]
block = "battery"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
