[global_config]
  broadcast_default = off
  enabled_plugins = MavenPluginURLHandler,
  geometry_hinting = True
[keybindings]
[layouts]
  [[default]]
    [[[child1]]]
      parent = window0
      type = Terminal
    [[[window0]]]
      parent = ""
      type = Window
[plugins]
[profiles]
  [[default]]
    cursor_color = "#aaaaaa"
    font = Fira Code Regular 12
    scrollback_lines = 50000
    show_titlebar = False
    use_system_font = False
    word_chars = "-,./?%&#:_~"
