# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelPackages = pkgs.linuxPackages_latest.extend (lpSelf: lpSuper: {
    rtl8821au = lpSuper.rtl8821au.overrideAttrs (rtl8821auOld: rec {
      src = pkgs.fetchFromGitHub {
        owner = "morrownr";
        repo = "8821au-20210708";
        rev = "6cd61cfce48218c26b57db4733aa0d3cbf9a2f2c";
        hash = "sha256-3A/Kn50UB2RyEOqe/p1FPKP2Nfg3NbtuHo7RsTYGaLY";
      };
    });
  });
  boot.kernelModules = [
    # fix hwmon drivers to avoid random device ids disturbing fancontrol
    "coretemp"
    "dell_smm_hwmon"

    "kvm-intel"
    "8821au"
  ];
  boot.extraModulePackages = with config.boot.kernelPackages; [
    rtl8821au
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/root";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-label/home";
    fsType = "ext4";
  };

  fileSystems."/home/guest/torrent" = {
    device = "/dev/disk/by-label/torrent";
    fsType = "ext4";
  };

  swapDevices = [
   { device = "/dev/disk/by-label/swap"; }
  ];

  nix.settings.max-jobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
