[theme]
theme = "solarized-dark"
[icons]
icons = "awesome6"

[[block]]
block = "service_status"
service = "openvpn-home"
active_format = " VPN 🔒 "
inactive_format = " VPN 🔓 "

[[block]]
block = "net"
device = "^wireless$"
format_alt = " $icon $ip $ssid $signal_strenght "

#[[block]]
#block = "net"
#device = "^ethernet$"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
warning = 10.0
alert = 5.0
format = " $icon root $available "
format_alt = " $icon $available / $total "

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
warning = 10.0
alert = 5.0
format = " $icon home $available "
format_alt = " $icon $available / $total "

[[block]]
block = "temperature"
format = " $icon $max "
good = 20
idle = 55
info = 70
warning = 80
chip = "*-isa-*"

[[block]]
block = "cpu"

[[block]]
block = "load"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"

[[block]]
block = "battery"
device = "BAT1"

[[block]]
block = "time"
