theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "wireless"

[[block]]
block = "net"
device = "aukey-ethernet"
hide_missing = true

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 60
warning = 1.0
alert = 0.5

[[block]]
block = "disk_space"
path = "/home"
alias = "home"
info_type = "available"
unit = "GB"
interval = 60
warning = 10.0
alert = 5.0

[[block]]
block = "disk_space"
path = "/var/lib/docker"
alias = "docker"
info_type = "available"
unit = "GB"
interval = 60
warning = 3.0
alert = 1.0

[[block]]
block = "disk_space"
path = "/nix"
alias = "nix"
info_type = "available"
unit = "GB"
interval = 60
warning = 7.0
alert = 3.0

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}°C"
chip = "*-isa-*"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}%"
format_swap = "{swap_used_percents}%"

[[block]]
block = "sound"

[[block]]
block = "battery"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
