language: nix

os:
  - linux
  - osx

before_script:
  - mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER

script:
  - ./format -c
  - nix-shell . -A install
  - nix-shell --pure tests -A run.all
