name: "Build systems"
on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron:  '55 5 * * 1'
env:
  NIXPKGS_ALLOW_UNFREE: 1
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        system_name:
          #- laptop
          - tv
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.4
    - name: Install nix
      uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-23.11
    - name: Setup cachix
      uses: cachix/cachix-action@v14
      with:
        name: jeremiehuchet
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Setup channels
      run: |
        # fetch pinned channels
        ./pinned-channels/fetch.sh
        # set NIX_PATH
        echo NIX_PATH=$(nix-instantiate --eval --expr '(builtins.concatStringsSep ":" (import ./pinned-channels).nixPath)' | sed -e 's/^"//' -e 's/"$//') >> $GITHUB_ENV
        # mock secrets
        ./.github/mock-secrets.sh
        # disable virtualbox, it takes too much time to build
        sed -i '/virtualisation\.virtualbox\.host\.enable = true/d' hosts/*.nix;
        # remove android studio, it takes too much space on github action executor
        sed -i '/android-studio/d' home/dev.nix;
    - name: Build system
      run: |
        echo $NIX_PATH
        nix-build --show-trace '<nixpkgs/nixos>' -A system -k -I nixos-config=$PWD/hosts/${{ matrix.system_name }}.nix
