name: "Build systems"
on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron:  '55 5 * * 1'
env:
  NIXPKGS_ALLOW_UNFREE: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
    - name: Install nix
      uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - name: Setup cachix
      uses: cachix/cachix-action@v8
      with:
        name: jeremiehuchet
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Setup channels
      run: |
        # set NIX_PATH
        echo NIX_PATH=$(nix eval --raw '(builtins.concatStringsSep ":" (import ./pinned-channels).nixPath)') >> "$GITHUB_ENV"
        # mock secrets
        ./.github/mock-secrets.sh
        # disable virtualbox, it takes too much time to build
        sed -i '/virtualisation\.virtualbox\.host\.enable = true/d' hosts/*.nix;
    - name: Build tv system
      run: nix-build '<nixpkgs/nixos>' -A system -k -I nixos-config=hosts/tv.nix
    - name: Build laptop system
      run: nix-build '<nixpkgs/nixos>' -A system -k -I nixos-config=hosts/laptop.nix
